### PR TITLE
fix error on missing high_drift

### LINKED ISSUE #127: Duration not parsing correctly
On your latest tag v2.7.0 as well as master and tag v2.6.1 the following happens:

```
> curl 'http://127.0.0.1:12345/metrics?duration=10s&protocol=4&target=time.cloudflare.com'
time: invalid duration ""
> echo wat\?
wat?
> curl 'http://127.0.0.1:12345/metrics?duration=10&protocol=4&target=time.cloudflare.com'
time: missing unit in duration "10"
```

Am  I missing something here? I  am on FreeBSD 13.4 and I have installed  go 1.23 here. This  is a manual build to keep ports tree issues out of the direct way, but the same thing  happens if I make a port skeleton and build this  package inside the ports  system.

BTW tag v2.5.0 works with go121 just fine.

### PR DESCRIPTION
**Pull request by majewsky**
Fixes #127.

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -120,18 +121,20 @@ func handlerMetrics(w http.ResponseWriter, r *http.Request) {
 			p = int(v)
 		}
 
-		if t, err := time.ParseDuration(r.URL.Query().Get("duration")); err == nil {
+		if t, err := time.ParseDuration(query.Get("duration")); err == nil {
 			d = t
 		} else {
-			http.Error(w, err.Error(), http.StatusBadRequest)
+			http.Error(w, "while parsing high_drift: "+err.Error(), http.StatusBadRequest)
```
Comment (SuperSandro2000) [inline main.go:127]:
```suggestion
			http.Error(w, "while parsing duration: "+err.Error(), http.StatusBadRequest)
```

**Review by SuperSandro2000 — APPROVED** [review]
